
set text to {{
Today's price updates:
10 oz. can of tuna $5
12 eggs for $2.98, 18 for $4.25
5 lb potatoes $3, 100 lbs $53.47
}}

set price to <{dollarSign: "$"}, {number: lots of digits then preferably ("." , digits greedily)}>

put text
put -

repeat with each match of price in text in reverse order
	if it.number doesn't contain "." then put ".00" after chars it.number_range of text
end repeat

put text
