
set text to {{
Today's price updates:
10 oz. can of tuna $5.08
12 eggs for $2.98, 18 for $4.25
5 lb potatoes $3, 100 lbs $53.47
}}

set number to <one or more digits then maybe ("." , digits)>

put every occurrence of number in text

// So when will a lazy quantifier ever match multiple characters?

put number matches "1"
put number matches "12345"
put number matches "2.98"

put every occurrence of <number at end of line> in text
